config/routes.rb
Rails.application.routes.draw do
  resources :watchlists
  resources :searches

  root to: 'searches#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/search.rb
class Search < ApplicationRecord
end

app/models/watchlist.rb
class Watchlist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  before_action :set_search, only: [:show, :edit, :update, :destroy]

  # GET /searches
  # GET /searches.json
  def index
    console
    @api_key = ENV['OMDB_API_KEY']
    @searches = Search.all

    @title = ""
    @year = ""
    
    @movie = params["watchlist"]
    
    if @movie.present?
      @title = @movie["title"]
      @year = @movie["year"]
    end

    unless @title.ascii_only? then
      @title = @title.delete!("^\u{0000}-\u{007F}")
    end
    unless @year.ascii_only? then
      @year = @year.delete!("^\u{0000}-\u{007F}")
    end
    
    if @year.nil?
      @datas = HTTParty.get('http://www.omdbapi.com/?apikey='+@api_key+'&t='+@title)
    elsif @title.nil?
      @datas = HTTParty.get('http://www.omdbapi.com/?apikey='+@api_key+'&y='+@year)
    elsif @title.nil? & @year.nil?
      @title = "Avengers" # Sample Movie from DataBase
      @year = "2012"      # Sample Movie from DataBase
      @datas = HTTParty.get('http://www.omdbapi.com/?apikey='+@api_key+'&t='+@title+'&y='+@year)
    else
      @datas = HTTParty.get('http://www.omdbapi.com/?apikey='+@api_key+'&t='+@title+'&y='+@year)
    end
    
    #resp.body # => displays body of the response
    
    @parsed_json = JSON.parse(@datas.body) # => parses JSON if you need to parse it

  end

  # GET /searches/1
  # GET /searches/1.json
  def show
  end

  # GET /searches/new
  def new
    @search = Search.new
  end

  # GET /searches/1/edit
  def edit
  end

  # POST /searches
  # POST /searches.json
  def create
    @search = Search.new(search_params)

    respond_to do |format|
      if @search.save
        format.html { redirect_to @search, notice: 'Search was successfully created.' }
        format.json { render :show, status: :created, location: @search }
      else
        format.html { render :new }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /searches/1
  # PATCH/PUT /searches/1.json
  def update
    respond_to do |format|
      if @search.update(search_params)
        format.html { redirect_to @search, notice: 'Search was successfully updated.' }
        format.json { render :show, status: :ok, location: @search }
      else
        format.html { render :edit }
        format.json { render json: @search.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /searches/1
  # DELETE /searches/1.json
  def destroy
    @search.destroy
    respond_to do |format|
      format.html { redirect_to searches_url, notice: 'Search was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_search
      @search = Search.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def search_params
      params.require(:watchlist).permit(:title, :year)
    end
end

app/controllers/watchlists_controller.rb
class WatchlistsController < ApplicationController
  before_action :set_watchlist, only: [:show, :edit, :update, :destroy]

  # GET /watchlists
  # GET /watchlists.json
  def index
    console
    @watchlists = Watchlist.all
  end

  # GET /watchlists/1
  # GET /watchlists/1.json
  def show
  end

  # GET /watchlists/new
  def new
    @watchlist = Watchlist.new
  end

  # GET /watchlists/1/edit
  def edit
  end

  # POST /watchlists
  # POST /watchlists.json
  def create
    @watchlist = Watchlist.new(watchlist_params)

    respond_to do |format|
      if @watchlist.save
        format.html { redirect_to watchlists_url, notice: 'Item was successfully added.' }
        format.json { render :show, status: :created, location: @watchlist }
      else
        format.html { render :new }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /watchlists/1
  # PATCH/PUT /watchlists/1.json
  def update
    respond_to do |format|
      if @watchlist.update(watchlist_params)
        format.html { redirect_to @watchlist, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @watchlist }
      else
        format.html { render :edit }
        format.json { render json: @watchlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /watchlists/1
  # DELETE /watchlists/1.json
  def destroy
    @watchlist.destroy
    respond_to do |format|
      format.html { redirect_to watchlists_url, notice: 'Item was successfully removed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_watchlist
      @watchlist = Watchlist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def watchlist_params
      params.require(:watchlist).permit(:title, :year, :director, :genre, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/watchlists_helper.rb
module WatchlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieListApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/searches/_form.html.erb
<%= simple_form_for(@search) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :year %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/searches/edit.html.erb
<h1>Editing Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Show', @search %> |
<%= link_to 'Back', searches_path %>

app/views/searches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Search</h1>
<h1><a href="/watchlists">Watchlist</a></h1>

      <%= simple_form_for :watchlist, url: root_path, method: "GET", html: { class: 'form-inline' } do |f| %>
        <%= f.input :title, input_html: {value: ""} %>
	      <%= f.input :year, :required => false, input_html: {value: ""} %>
        <%= f.button  :submit , "Search" %>
      <% end %>


    <% if @parsed_json["Response"] == "True" %>

        <p> Title : <%= @parsed_json["Title"] %>        </p>
        <p> Year : <%= @parsed_json["Year"]     %>      </p>
        <p> Director : <%= @parsed_json["Director"] %>  </p>
        <p> Genre : <%= @parsed_json["Genre"]    %>     </p>

        <% if @parsed_json["Ratings"].nil? |  @parsed_json["Ratings"] != []  %>
          <p>Rating : <%= @parsed_json["imdbRating"] %></p>
          <% @watchlist = Watchlist.new(title: @parsed_json["Title"] ,year: @parsed_json["Year"],
                director: @parsed_json["Director"], genre: @parsed_json["Genre"], 
                rating: @parsed_json["imdbRating"] ) %>
        <% else %>
          <p>Source : <%= @parsed_json["Ratings"].first["Source"] %></p>
          <p>Rating : <%= @parsed_json["Ratings"].first["Value"] %></p>
          <% @watchlist = Watchlist.new(title: @parsed_json["Title"] ,year: @parsed_json["Year"],
                director: @parsed_json["Director"], genre: @parsed_json["Genre"], 
                rating: @parsed_json["Ratings"].first["Value"] ) %>
        <% end %>

      
      <% item = Watchlist.find_by(title: @parsed_json["Title"]) %>
      <% if item.nil? %>
        <%= render :partial => 'watchlists/form' ,locals: { watchlist: item}  %>
      <% else %>
      <td><%= button_to 'Remove Item', item, method: :delete, data: { confirm: "Delete #{item["title"]}?" } %></td>
      <% end %>
    <% elsif @parsed_json["Response"] == "False" %>
        </br></br></br>
        <% if @title == "" && @year == "" %>
          <p>Use Search!</p>
        <% elsif @title == "" %>
          <p>Enter title</p>
        <% else %>
          <%= @parsed_json["Error"]  %>
        <% end %>
    <% else %>
      <p> Use Search! </p>
    <% end %>

app/views/searches/new.html.erb
<h1>New Search</h1>

<%= render 'form', search: @search %>

<%= link_to 'Back', searches_path %>

app/views/searches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @search.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @search.year %>
</p>

<%= link_to 'Edit', edit_search_path(@search) %> |
<%= link_to 'Back', searches_path %>

app/views/watchlists/_form.html.erb
<%= simple_form_for(@watchlist) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title    ,as: :hidden ,input_html: { value: f.object.title     || @watchlist.title     } %>
    <%= f.input :year     ,as: :hidden ,input_html: { value: f.object.year      || @watchlist.year      } %>
    <%= f.input :director ,as: :hidden ,input_html: { value: f.object.director  || @watchlist.director  } %>
    <%= f.input :genre    ,as: :hidden ,input_html: { value: f.object.genre     || @watchlist.genre     } %>
    <%= f.input :rating   ,as: :hidden ,input_html: { value: f.object.rating    || @watchlist.rating    } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , "Add Item" , class: 'btn btn-primary' , data: { disable_with: "Adding #{@watchlist.title}..." } %>
  </div>
<% end %>

app/views/watchlists/edit.html.erb
<h1>Editing Watchlist</h1>

<%= render 'form', watchlist: @watchlist %>

<%= link_to 'Show', @watchlist %> |
<%= link_to 'Back', watchlists_path %>

app/views/watchlists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Watchlists</h1>
<h1><a href="/searches">Search</a></h1>


<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Year</th>
      <th>Director</th>
      <th>Genre</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @watchlists.each do |watchlist| %>
      <tr>
        <td><%= watchlist.title %></td>
        <td><%= watchlist.year %></td>
        <td><%= watchlist.director %></td>
        <td><%= watchlist.genre %></td>
        <td><%= watchlist.rating %></td>
        <td><% link_to 'Show', watchlist %></td>
        <td><% link_to 'Edit', edit_watchlist_path(watchlist) %></td>
        <td><%= button_to 'Remove Item', watchlist, method: :delete, data: { confirm: "Delete #{watchlist["title"]}?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/watchlists/new.html.erb
<h1>New Watchlist</h1>

<%= render 'form', watchlist: @watchlist %>

<%= link_to 'Back', watchlists_path %>

app/views/watchlists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @watchlist.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @watchlist.year %>
</p>

<p>
  <strong>Director:</strong>
  <%= @watchlist.director %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @watchlist.genre %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @watchlist.rating %>
</p>

<%= link_to 'Edit', edit_watchlist_path(@watchlist) %> |
<%= link_to 'Back', watchlists_path %>